sensors:
# band
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, 0.75, 0.91]
      rpy: [0, 0, 'pi']
  band_logic_camera:
    type: logical_camera
    pose:
      xyz: [1.21, 0.9, 1.6]
      rpy: [0, 'pi/2', 0]

# bins
  bin1_camera:
    type: logical_camera
    pose:
      xyz: [-0.3, 1.916, 1.6]
      rpy: [0, 'pi/2', 0]
  bin2_camera:
    type: logical_camera
    pose:
      xyz: [-0.3, 1.15, 1.6]
      rpy: [0, 'pi/2', 0]
  bin3_camera:
    type: logical_camera
    pose:
      xyz: [-0.3, 0.383, 1.6]
      rpy: [0, 'pi/2', 0]
  bin4_camera:
    type: logical_camera
    pose:
      xyz: [-0.3, -0.383, 1.6]
      rpy: [0, 'pi/2', 0]
  bin5_camera:
    type: logical_camera
    pose:
      xyz: [-0.3, -1.15, 1.6]
      rpy: [0, 'pi/2', 0]
  bin6_camera:
    type: logical_camera
    pose:
      xyz: [-0.3, -1.916, 1.6]
      rpy: [0, 'pi/2', 0]

# agv's
  logical_camera_8:
    type: logical_camera
    pose:
      xyz: [0.3, 3.15, 1.5]
      rpy: [0, 'pi/2', 0]
  logical_camera_9:
    type: logical_camera
    pose:
      xyz: [0.3, -3.15, 1.5]
      rpy: [0, 'pi/2', 0]


